# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Set Release version env variable
      run: |
        echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Copy artefacts
      run: mkdir staging && cp target/*.jar staging

    - name: Upload Artefacts 
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging

    #- name: Publish to GitHub Packages Apache Maven
    #  run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
    #  env:
    #    GITHUB_TOKEN: ${{ github.token }}

    #- name: upload release artifact
    # uses: actions/upload-release-asset@v1
    #  env:
    #    GITHUB_TOKEN: ${{ github.token }}
    #  with:
    #    upload_url: ${{ steps.create_release.outputs.upload_url }}
    #    asset_path: ./kafka-connect-loosehangerjeans-source-${{ env.RELEASE_VERSION }}-jar-with-dependencies.jar
    #    asset_name: kafka-connect-loosehangerjeans-source-jar-with-dependencies.jar
    #    asset_content_type: application/jar
